# Generated by Django 2.2.2 on 2019-06-20 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190620_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_study', to='courses.Group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
