# Generated by Django 2.2.2 on 2019-06-20 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190620_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(default='00:05:00'),
        ),
        migrations.AlterField(
            model_name='course',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='test',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_test', to='courses.CourseTest'),
        ),
    ]
