# Generated by Django 2.2.2 on 2019-06-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190620_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(default='30:00:00'),
        ),
        migrations.AlterField(
            model_name='course',
            name='test',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course_test', to='courses.CourseTest'),
            preserve_default=False,
        ),
    ]
