# Generated by Django 2.2.2 on 2019-06-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190620_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group_study', to='courses.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='score',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='test',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_test', to='courses.CourseTest'),
        ),
    ]
