# Generated by Django 2.2.2 on 2019-06-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190620_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_study', to='courses.Group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_test', to='courses.CourseTest'),
        ),
    ]
