# Generated by Django 2.2.2 on 2019-06-24 06:41

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190623_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='images', validators=[courses.validators.validate_image_size]),
        ),
    ]
